include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_const_declarations
    - unnecessary_null_in_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - prefer_collection_literals
    - unnecessary_this
    - prefer_final_fields
    - prefer_final_locals
    - avoid_redundant_argument_values

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
