// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBOgnTLSDkDr9LV4-sQyFWqdmLTtUrh8',
    appId: '1:281520916928:web:9c5d8daffc4b5439036025',
    messagingSenderId: '281520916928',
    projectId: 'safe-lending',
    authDomain: 'safe-lending.firebaseapp.com',
    storageBucket: 'safe-lending.firebasestorage.app',
    measurementId: 'G-CET47BKTPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBOgnTLSDkDr9LV4-sQyFWqdmLTtUrh8',
    appId: '1:281520916928:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '281520916928',
    projectId: 'safe-lending',
    storageBucket: 'safe-lending.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBOgnTLSDkDr9LV4-sQyFWqdmLTtUrh8',
    appId: '1:281520916928:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '281520916928',
    projectId: 'safe-lending',
    storageBucket: 'safe-lending.firebasestorage.app',
    iosBundleId: 'com.tpln.app',
  );
}
